export const HN_API_BASE_URL = 'https://hacker-news.firebaseio.com/v0'
export const HN_ITEM_URL_PREFIX = 'https://news.ycombinator.com/item?id='

export const WEEKLY_DAY_AI = Object.freeze({
  name: '星期天AI',
  englishName: 'Weekly Day AI',
  url: 'https://www.weekly-day.top/',
  disclosure: Object.freeze({
    zh: '本文使用星期天AI中转站大模型，基于 Hacker News 内容自动生成。',
    en: 'This article was automatically generated by the Weekly Day AI gateway model using content from Hacker News.',
  }),
})
