import type { Locale, Post, PostBlock, PostDisclosure, PostGeneration, PostSource } from './posts'

const WEEKLY_DAY_AI_URL = 'https://www.weekly-day.top/'
const FIXED_DISCLOSURE: PostDisclosure = {
  zh: '本文使用星期天AI中转站大模型，基于 Hacker News 内容自动生成。',
  en: 'This article was automatically generated by the Weekly Day AI gateway model using content from Hacker News.',
}

const generatedFiles = import.meta.glob('./generated-posts/*.json', {
  eager: true,
  query: '?raw',
  import: 'default',
}) as Record<string, string>

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}

function nonEmptyString(value: unknown, path: string): string {
  if (typeof value !== 'string' || !value.trim()) throw new Error(path + ' 必须是非空字符串')
  return value.trim()
}

function positiveInteger(value: unknown, path: string): number {
  if (!Number.isInteger(value) || (value as number) <= 0) throw new Error(path + ' 必须是正整数')
  return value as number
}

function nonNegativeNumber(value: unknown, path: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) throw new Error(path + ' 必须是非负数字')
  return value
}

function validDateString(value: unknown, path: string): string {
  const date = nonEmptyString(value, path)
  if (Number.isNaN(Date.parse(date))) throw new Error(path + ' 必须是有效日期')
  return date
}

function httpUrl(value: unknown, path: string): string {
  const url = nonEmptyString(value, path)
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    throw new Error(path + ' 必须是有效 URL')
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') throw new Error(path + ' 必须使用 HTTP 或 HTTPS')
  return url
}

function localizedText(value: unknown, path: string): Record<Locale, string> {
  if (!isRecord(value)) throw new Error(path + ' 必须同时包含 zh 和 en')
  return {
    zh: nonEmptyString(value.zh, path + '.zh'),
    en: nonEmptyString(value.en, path + '.en'),
  }
}

function localizedTags(value: unknown, path: string): Record<Locale, string[]> {
  if (!isRecord(value)) throw new Error(path + ' 必须同时包含 zh 和 en 数组')
  const result = {} as Record<Locale, string[]>
  for (const locale of ['zh', 'en'] as const) {
    if (!Array.isArray(value[locale])) throw new Error(path + '.' + locale + ' 必须是数组')
    const tags = value[locale].map((tag, index) => nonEmptyString(tag, path + '.' + locale + '[' + index + ']'))
    if (tags.length < 1 || tags.length > 6) throw new Error(path + '.' + locale + ' 必须包含 1 到 6 个标签')
    result[locale] = [...new Set(tags)]
  }
  return result
}

function postBlocks(value: unknown, path: string): Record<Locale, PostBlock[]> {
  if (!isRecord(value)) throw new Error(path + ' 必须同时包含 zh 和 en 内容')
  const result = {} as Record<Locale, PostBlock[]>
  for (const locale of ['zh', 'en'] as const) {
    if (!Array.isArray(value[locale]) || value[locale].length < 1) throw new Error(path + '.' + locale + ' 必须是非空数组')
    let headingCount = 0
    result[locale] = value[locale].map((block, index) => {
      const blockPath = path + '.' + locale + '[' + index + ']'
      if (!isRecord(block)) throw new Error(blockPath + ' 必须是对象')
      const type = block.type
      if (type === 'heading' || type === 'paragraph' || type === 'quote') {
        if (type === 'heading') headingCount += 1
        return { type, text: localizedText(block.text, blockPath + '.text') } as PostBlock
      }
      if (type === 'code') {
        return {
          type,
          language: nonEmptyString(block.language, blockPath + '.language'),
          code: nonEmptyString(block.code, blockPath + '.code'),
        } as PostBlock
      }
      throw new Error(blockPath + '.type 类型不受支持')
    })
    if (headingCount < 1) throw new Error(path + '.' + locale + ' 至少需要一个 heading')
  }
  return result
}

function postSource(value: unknown): PostSource {
  if (!isRecord(value)) throw new Error('source 必须是对象')
  const hnId = positiveInteger(value.hnId, 'source.hnId')
  const hnUrl = httpUrl(value.hnUrl, 'source.hnUrl')
  const hnParsed = new URL(hnUrl)
  if (hnParsed.hostname !== 'news.ycombinator.com' || hnParsed.pathname !== '/item' || !hnParsed.searchParams.get('id')) {
    throw new Error('source.hnUrl 必须是 Hacker News 讨论链接')
  }
  const originalUrl = httpUrl(value.originalUrl, 'source.originalUrl')
  return {
    hnId,
    hnUrl,
    originalUrl,
    title: nonEmptyString(value.title, 'source.title'),
    author: nonEmptyString(value.author, 'source.author'),
    score: nonNegativeNumber(value.score, 'source.score'),
    commentCount: nonNegativeNumber(value.commentCount, 'source.commentCount'),
    publishedAt: validDateString(value.publishedAt, 'source.publishedAt'),
  }
}

function postGeneration(value: unknown): PostGeneration {
  if (!isRecord(value)) throw new Error('generation 必须是对象')
  const provider = nonEmptyString(value.provider, 'generation.provider')
  if (provider !== 'Weekly Day AI') throw new Error('generation.provider 必须是 Weekly Day AI')
  const providerUrl = httpUrl(value.providerUrl, 'generation.providerUrl')
  if (providerUrl !== WEEKLY_DAY_AI_URL) throw new Error('generation.providerUrl 必须是 Weekly Day AI 官网')
  return {
    provider,
    providerUrl,
    model: nonEmptyString(value.model, 'generation.model'),
    generatedAt: validDateString(value.generatedAt, 'generation.generatedAt'),
  }
}

function postDisclosure(value: unknown): PostDisclosure {
  const disclosure = localizedText(value, 'post.disclosure')
  if (disclosure.zh !== FIXED_DISCLOSURE.zh || disclosure.en !== FIXED_DISCLOSURE.en) {
    throw new Error('post.disclosure 与固定披露文案不一致')
  }
  return disclosure
}

export function isGeneratedPostDocument(value: unknown): boolean {
  if (!isRecord(value) || value.schemaVersion !== 1 || !isRecord(value.post)) return false
  try {
    postSource(value.source)
    postGeneration(value.generation)
    postDisclosure(value.post.disclosure)
    return true
  } catch {
    return false
  }
}

export function parseGeneratedPostFile(filePath: string, raw: string): Post | null {
  try {
    const document: unknown = JSON.parse(raw)
    if (!isRecord(document) || document.schemaVersion !== 1) throw new Error('schemaVersion 必须为 1')
    const source = postSource(document.source)
    const generation = postGeneration(document.generation)
    if (!isRecord(document.post)) throw new Error('post 必须是对象')
    const post = document.post
    const slug = nonEmptyString(post.slug, 'post.slug')
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error('post.slug 必须是小写 slug')
    const date = nonEmptyString(post.date, 'post.date')
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('post.date 必须是 YYYY-MM-DD')
    const title = localizedText(post.title, 'post.title')
    const excerpt = localizedText(post.excerpt, 'post.excerpt')
    const category = localizedText(post.category, 'post.category')
    const tags = localizedTags(post.tags, 'post.tags')
    const content = postBlocks(post.content, 'post.content')
    const disclosure = postDisclosure(post.disclosure)
    const readingTime = post.readingTime
    if (!Number.isInteger(readingTime) || readingTime < 1) throw new Error('post.readingTime 必须是正整数')
    return {
      slug,
      date,
      readingTime,
      category,
      tags,
      title,
      excerpt,
      content,
      disclosure,
      source,
      generation,
      isGenerated: true,
    }
  } catch (error) {
    console.warn('[generated-posts] 跳过 ' + filePath + ': ' + (error instanceof Error ? error.message : String(error)))
    return null
  }
}

const seenHnIds = new Set<number>()
const seenSlugs = new Set<string>()

export const generatedPosts: Post[] = Object.entries(generatedFiles)
  .sort(([left], [right]) => left.localeCompare(right))
  .map(([filePath, raw]) => parseGeneratedPostFile(filePath, raw))
  .filter((post): post is Post => {
    if (!post) return false
    if (seenHnIds.has(post.source?.hnId ?? 0)) {
      console.warn('[generated-posts] 跳过重复 Hacker News 文章: ' + post.slug)
      return false
    }
    if (seenSlugs.has(post.slug)) {
      console.warn('[generated-posts] 跳过重复 slug: ' + post.slug)
      return false
    }
    seenHnIds.add(post.source?.hnId ?? 0)
    seenSlugs.add(post.slug)
    return true
  })
